version: '3.9'

volumes:
  pgdata:

services:

  postgredb:
    image: postgres:latest
    environment:
      POSTGRES_DB: "ads"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Tehn89tehn"

  python_service:
    build: .
    command: bash -c "python3 models.py && python3 server.py"
    environment:
      - MY_ENV=aiohttp
    expose:
      - 8080
    depends_on:
      - postgredb