# примеры API-запросов

@baseUrl = http://localhost/

# создание объявления
POST {{baseUrl}}/ads/
Content-Type: application/json

{
  "head": "Motok4",
  "description": "111",
  "username": "anapa2@ya.ru",
  "password": "12345678"
}

###

# получение объявления
GET {{baseUrl}}/ads/3
Content-Type: application/json

###

# обновление объявления
PATCH {{baseUrl}}/ads/2
Content-Type: application/json

{
  "head": "5",
  "description": "4",
  "username": "anapa1@ya.ru",
  "password": "87654321"
}

###

# удаление объявления
DELETE {{baseUrl}}/ads/2
Content-Type: application/json

{
  "username": "anapa1@ya.ru",
  "password": "87654321"
}

###

# создание пользователя
POST {{baseUrl}}/user/
Content-Type: application/json

{
  "email": "anapa3@ya.ru",
  "password": "12345678"
  
}

###

# получение пользователя
GET {{baseUrl}}/user/1
Content-Type: application/json

###

# изменение пользователя
PATCH {{baseUrl}}/user/3
Content-Type: application/json

{
  "email": "sochi3@ya.ru",
  "password": "12345678"
  
}
